set role postgres;
DROP TABLE IF EXISTS employees CASCADE;
CREATE TABLE employees (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar
);

DROP TABLE IF EXISTS projects CASCADE;
CREATE TABLE projects (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    name varchar,
    release_date date
);

DROP TABLE IF EXISTS employees_projects;
CREATE TABLE employees_projects(
    employee_id integer,
    project_id integer,
    FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE ON UPDATE CASCADE
);


insert into employees(name) values('Иванов');
insert into employees(name) values('Петров');
insert into employees(name) values('Чащин');

insert into projects(name, release_date) values ('Калькулятор', '01-01-2001');
insert into projects(name, release_date) values ('World of Warcraft', '01-02-2001');
insert into projects(name, release_date) values ('Warcraft of World', '01-03-2001');


insert into employees_projects(employee_id, project_id) values (1, 1);
insert into employees_projects(employee_id, project_id) values (1, 2);
insert into employees_projects(employee_id, project_id) values (2, 2);
insert into employees_projects(employee_id, project_id) values (3, 3);


drop owned by admin;
drop user if exists admin;
CREATE USER admin WITH PASSWORD 'admin';

drop OWNED BY hr;
drop user if exists hr;
CREATE USER hr WITH PASSWORD 'hr';

drop owned by employee;
drop user if exists employee;
CREATE USER employee WITH PASSWORD 'employee';

drop owned by project_manager;
drop user if exists project_manager;
CREATE USER project_manager WITH PASSWORD 'project_manager';


grant usage on schema schema8 to admin;
GRANT ALL PRIVILEGES ON TABLE employees_projects TO admin;
GRANT ALL PRIVILEGES ON TABLE employees TO admin;
grant all PRIVILEGES on table projects to admin;


grant usage on schema schema8 to hr;
GRANT all PRIVILEGES on table employees to hr;


grant usage on schema schema8 to employee;
grant select on table projects to employee;
grant select on table protected_projects to employee;

grant usage on schema schema8 to project_manager;
grant select on table employees to project_manager;
grant all privileges on table projects to project_manager;
grant all privileges on table employees_projects to project_manager;

drop owned by "Иванов";
drop user if exists "Иванов";
create user "Иванов" with password 'Иванов' in role employee;

RESET role;

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

create or replace view protected_projects as select * from projects
where projects.id IN (SELECT employees_projects.project_id FROM employees inner join employees_projects ON employees.id = employees_projects.employee_id
                                    --INNER JOIN projects ON projects.id = employees_projects.project_id
                                    where employees.name = current_user);

select * from protected_projects;

/*CREATE POLICY proj_employees ON projects
    FOR SELECT TO employee
    USING (projects.id IN (SELECT employees_projects.project_id FROM employees inner join employees_projects ON employees.id = employees_projects.employee_id
                                    --INNER JOIN projects ON projects.id = employees_projects.project_id
                                    where employees.name = current_user))
;*/

GRANT employee to "Иванов";

set role "Иванов";

select * from projects;
select * from projects where name = 'Калькулятор' or name = 'World of Warcraft';

SET ROLE employee;

SELECT * FROM employees;
SELECT * FROM projects;
SELECT * FROM employees_projects;

UPDATE projects set name = 'Майнкрафт' where name = 'World of Warcraft';
UPDATE employees_projects set project_id = 1 where employee_id = 3 and employee_id = 3;
UPDATE employees set name = 'Пащак' where name = 'Чащин';

INSERT INTO projects(name) values ('Дороро');
INSERT INTO employees(name) values ('Минин');
INSERT INTO employees_projects values(2, 1);

DELETE FROM projects where True;
DELETE FROM employees_projects WHERE TRUE;
DELETE FROM employees where true;

GRANT employee TO "Иванов";

RESET ROLE ;

drop view protected_projects

SET ROLE "Иванов";

SELECT * FROM employees;
SELECT * FROM projects;
SELECT * FROM employees_projects;

UPDATE projects set name = 'Майнкрафт' where name = 'World of Warcraft';
UPDATE employees_projects set project_id = 1 where employee_id = 3 and employee_id = 3;
UPDATE employees set name = 'Пащак' where name = 'Чащин';

INSERT INTO projects(name) values ('Дороро');
INSERT INTO employees(name) values ('Минин'); -- PROBLEMA
INSERT INTO employees_projects values(2, 1);

DELETE FROM projects where True;
DELETE FROM employees_projects WHERE TRUE;
DELETE FROM employees where name = 'Иванов';

SELECT * FROM employees;
select * from employees_projects;

set role project_manager;

SELECT * FROM employees;
SELECT * FROM projects;
SELECT * FROM employees_projects;

INSERT INTO projects(name, release_date) values ('Дороро', '01-04-2001');
INSERT INTO employees(name) values ('Минин');
INSERT INTO employees_projects values(2, 1);

UPDATE projects set name = 'Doka 3' where name = 'Warcraft of World';
UPDATE employees_projects set project_id = 1 where employee_id = 3 and employee_id = 3;
UPDATE employees set name = 'Пащак' where name = 'Чащин';

DELETE FROM projects where name = 'Калькулятор';
DELETE FROM employees_projects WHERE project_id = 1;
DELETE FROM employees where true;

SELECT * FROM projects;
SELECT * FROM employees_projects;

set role admin;

SELECT * FROM employees;
SELECT * FROM projects;
SELECT * FROM employees_projects;

UPDATE projects set name = 'Doka 4' where name = 'Doka 3';
UPDATE employees_projects set project_id = 4 where employee_id = 2 and employee_id = 2;
UPDATE employees set name = 'Чащин' where name = 'Пащак';

INSERT INTO projects(name, release_date) values ('Бабуба', '01-05-2001');
INSERT INTO employees(name) values ('Коровьев');
INSERT INTO employees_projects values(4, 2);

DELETE from employees where id = 2;
DELETE From projects where name = 'Doka 4';
delete from employees_projects where employee_id = 2;

SELECT * FROM employees;
SELECT * FROM projects;
SELECT * FROM employees_projects;




